//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.19 at 09:53:29 PM SAST 
//


package com.thabo.sokodistrict.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the thabo.com.sokodistrict.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EmployeeLeaveQueryModel_QNAME = new QName("http://sokodistrict.com.thabo/model", "EmployeeLeaveQueryModel");
    private final static QName _LeaveDetailsQueryModel_QNAME = new QName("http://sokodistrict.com.thabo/model", "LeaveDetailsQueryModel");
    private final static QName _LeaveTypeQueryModel_QNAME = new QName("http://sokodistrict.com.thabo/model", "LeaveTypeQueryModel");
    private final static QName _LeaveBalanceQueryModel_QNAME = new QName("http://sokodistrict.com.thabo/model", "LeaveBalanceQueryModel");
    private final static QName _EmployeeDetailsQueryModel_QNAME = new QName("http://sokodistrict.com.thabo/model", "EmployeeDetailsQueryModel");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: thabo.com.sokodistrict.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LeaveBalanceQueryModel }
     * 
     */
    public LeaveBalanceQueryModel createLeaveBalanceQueryModel() {
        return new LeaveBalanceQueryModel();
    }

    /**
     * Create an instance of {@link EmployeeLeaveQueryModel }
     * 
     */
    public EmployeeLeaveQueryModel createEmployeeLeaveQueryModel() {
        return new EmployeeLeaveQueryModel();
    }

    /**
     * Create an instance of {@link LeaveDetailsQueryModel }
     * 
     */
    public LeaveDetailsQueryModel createLeaveDetailsQueryModel() {
        return new LeaveDetailsQueryModel();
    }

    /**
     * Create an instance of {@link LeaveTypeQueryModel }
     * 
     */
    public LeaveTypeQueryModel createLeaveTypeQueryModel() {
        return new LeaveTypeQueryModel();
    }

    /**
     * Create an instance of {@link EmployeeDetailsQueryModel }
     * 
     */
    public EmployeeDetailsQueryModel createEmployeeDetailsQueryModel() {
        return new EmployeeDetailsQueryModel();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmployeeLeaveQueryModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sokodistrict.com.thabo/model", name = "EmployeeLeaveQueryModel")
    public JAXBElement<EmployeeLeaveQueryModel> createEmployeeLeaveQueryModel(EmployeeLeaveQueryModel value) {
        return new JAXBElement<EmployeeLeaveQueryModel>(_EmployeeLeaveQueryModel_QNAME, EmployeeLeaveQueryModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LeaveDetailsQueryModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sokodistrict.com.thabo/model", name = "LeaveDetailsQueryModel")
    public JAXBElement<LeaveDetailsQueryModel> createLeaveDetailsQueryModel(LeaveDetailsQueryModel value) {
        return new JAXBElement<LeaveDetailsQueryModel>(_LeaveDetailsQueryModel_QNAME, LeaveDetailsQueryModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LeaveTypeQueryModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sokodistrict.com.thabo/model", name = "LeaveTypeQueryModel")
    public JAXBElement<LeaveTypeQueryModel> createLeaveTypeQueryModel(LeaveTypeQueryModel value) {
        return new JAXBElement<LeaveTypeQueryModel>(_LeaveTypeQueryModel_QNAME, LeaveTypeQueryModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LeaveBalanceQueryModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sokodistrict.com.thabo/model", name = "LeaveBalanceQueryModel")
    public JAXBElement<LeaveBalanceQueryModel> createLeaveBalanceQueryModel(LeaveBalanceQueryModel value) {
        return new JAXBElement<LeaveBalanceQueryModel>(_LeaveBalanceQueryModel_QNAME, LeaveBalanceQueryModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmployeeDetailsQueryModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sokodistrict.com.thabo/model", name = "EmployeeDetailsQueryModel")
    public JAXBElement<EmployeeDetailsQueryModel> createEmployeeDetailsQueryModel(EmployeeDetailsQueryModel value) {
        return new JAXBElement<EmployeeDetailsQueryModel>(_EmployeeDetailsQueryModel_QNAME, EmployeeDetailsQueryModel.class, null, value);
    }

}
